FROM golang:stretch as build
WORKDIR /go/src/github.com/OWASP/Amass1
RUN apt update && apt install -y git && go get -u github.com/OWASP/Amass/v3/...

# Build python worker for amass
FROM ubuntu:16.04
LABEL Name=amass_black Version=1.0.0

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update

RUN apt-get install -y \
    python3.6 \
    python3.6-dev \
    build-essential \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    python3-pip \
    vim

RUN python3.6 -m pip install --upgrade pip

WORKDIR /app
ADD . /app

RUN python3.6 -m pip install -r requirements.txt

CMD ["python3.6", "spawn_worker.py", "amass", "--config", "/app/config/config_docker.yml"]
